library(fixest)
library(broom)
library(haschaR)
library(tidyverse)
library(pbapply)
library(readxl)
library(data.table)
library(conflicted)
library(future.apply)
library(xtable)
library(haven)
library(pdftools)
library(magick)
library(MatchIt)
library(janitor)

conflicted::conflict_prefer(name = "filter", winner = "dplyr")
conflicted::conflict_prefer(name = "lag", winner = "dplyr")
conflicted::conflict_prefer(name = "first", winner = "dplyr")
